# Generated by Django 4.2.4 on 2024-03-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_area_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='cantidad_profesores',
            field=models.IntegerField(default=0),
        ),
    ]
