# Generated by Django 4.2.4 on 2024-03-29 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_distribucion_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucion',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='distribucion',
            unique_together={('area', 'producto')},
        ),
    ]
