# Generated by Django 4.2.4 on 2024-03-29 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.FloatField()),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.area')),
            ],
        ),
        migrations.CreateModel(
            name='PagosAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.FloatField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.defaultuser')),
            ],
        ),
    ]
