# Generated by Django 4.2.4 on 2024-03-29 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_pagosdistribucion_pagosasignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosasignacion',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.area'),
        ),
    ]
