# Generated by Django 4.2.4 on 2024-03-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_pagosasignacion_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
